{{- if .Values.externalSecrets.enabled | default true }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helicone-clickhouse-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "30s" | quote }}
  secretStoreRef:
    name: gcpsm-infra-test-03-2b45
    kind: ClusterSecretStore
  target:
    name: {{ .Values.helicone.config.clickhouseSecretsName | default (printf "%s-secrets" (include "clickhouse.name" .)) | quote }}
    type: Opaque
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix | default "helicone" }}-clickhouse
        property: user
{{- end }} 