{{- if .Values.externalSecrets.enabled | default false }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helicone-clickhouse-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "30s" | quote }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: helicone-helicone-core-clickhouse-secrets # TODO Don't hardcode this
    type: Opaque
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix | default "helicone" }}/clickhouse
        property: user
{{- end }} 