{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helicone-database-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: helicone-secrets-temp
    type: Opaque
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix }}/database
        property: postgres-password
    - secretKey: access_key
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix }}/storage
        property: access_key
    - secretKey: secret_key
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix }}/storage
        property: secret_key
    - secretKey: minio-root-user
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix }}/storage
        property: minio-root-user
    - secretKey: minio-root-password
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix }}/storage
        property: minio-root-password
{{- end }} 