{{- if .Values.externalSecrets.enabled | default true }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helicone-minio-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "30s" | quote }}
  secretStoreRef:
    name: gcpsm-infra-test-03-2b45
    kind: ClusterSecretStore
  target:
    name: helicone-minio-secrets
    type: Opaque
    creationPolicy: Owner
  data:
    - secretKey: root_user
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix | default "helicone" }}-storage
        property: minio-root-user
    - secretKey: root_password
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix | default "helicone" }}-storage
        property: minio-root-password
{{- end }} 