{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helicone-web-sync
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: helicone-web-secrets-temp
    type: Opaque
    creationPolicy: Owner
  data:
    - secretKey: BETTER_AUTH_SECRET
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix }}/web
        property: BETTER_AUTH_SECRET
    - secretKey: STRIPE_SECRET_KEY
      remoteRef:
        key: {{ .Values.externalSecrets.secretPrefix }}/web
        property: STRIPE_SECRET_KEY
{{- end }} 