# Minimal Kube-Prometheus-Stack Values for Development/Testing
# This configuration uses minimal resources and no persistence

# Reduce replica counts and resource usage
defaultRules:
  create: true
  rules:
    alertmanager: false
    etcd: false
    configReloaders: false
    general: true
    k8s: true
    kubeApiserver: false
    kubeApiserverAvailability: false
    kubeApiserverSlos: false
    kubelet: false
    kubeProxy: false
    kubePrometheusGeneral: false
    kubePrometheusNodeRecording: false
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: false
    kubernetesSystem: false
    kubeScheduler: false
    kubeStateMetrics: true
    network: false
    node: true
    nodeExporterAlerting: false
    nodeExporterRecording: false
    prometheus: false
    prometheusOperator: false

# Prometheus Operator - minimal resources
prometheusOperator:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
    requests:
      cpu: 50m
      memory: 50Mi
  # Disable admission webhooks to simplify deployment
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false

# Prometheus - minimal configuration
prometheus:
  enabled: true
  prometheusSpec:
    # Short retention for development
    retention: 3d
    retentionSize: "1GB"

    # Minimal resources
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

    # No persistence in minimal setup
    storageSpec: {}

    # Reduce scrape interval to save resources
    scrapeInterval: "60s"
    evaluationInterval: "60s"

    # Disable features not needed in dev
    enableAdminAPI: false
    enableFeatures: []

# Grafana - minimal configuration
grafana:
  enabled: true

  # Default admin credentials
  adminPassword: "admin"

  # No persistence
  persistence:
    enabled: false

  # Minimal resources
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

  # Sidecar for dashboards
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

  # NodePort for easy access without LoadBalancer
  service:
    type: NodePort
    nodePort: 30300

# AlertManager - disabled in minimal setup
alertmanager:
  enabled: false

# Exporters - only essential ones
nodeExporter:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 50Mi
    requests:
      cpu: 50m
      memory: 30Mi

kubeStateMetrics:
  enabled: true
  resources:
    limits:
      cpu: 100m
      memory: 64Mi
    requests:
      cpu: 50m
      memory: 32Mi

# Disable non-essential ServiceMonitors
kubeApiServer:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeEtcd:
  enabled: false
kubelet:
  enabled: true
  serviceMonitor:
    # Reduce metric cardinality
    metricRelabelings:
      - action: drop
        regex: container_cpu_usage_seconds_total
        sourceLabels:
          - __name__
      - action: drop
        regex: container_fs_.*
        sourceLabels:
          - __name__
      - action: drop
        regex: container_network_.*
        sourceLabels:
          - __name__
kubeProxy:
  enabled: false
coreDns:
  enabled: false
