################################################################################
#
#                            HELICONE CORE
#
################################################################################

global:
  postgresql:
    enabled: true
    auth:
      database: helicone_test
      username: postgres
      postgresPassword: "your-super-secret-and-long-postgres-password"
    primary:
      persistence:
        size: 5Gi
        storageClass: "gp2-immediate"

# - Aurora connection configuration
aurora:
  enabled: false
  host: "helicone-aurora-cluster.cluster-cr0pbknv3xbp.us-west-2.rds.amazonaws.com"
  port: 5432
  database: "helicone"
  username: "helicone_admin"
  # Password will be pulled from Kubernetes secret created from AWS Secrets Manager

helicone:
  # Required secrets configuration for template compatibility
  # IMPORTANT: These are placeholder values for template compatibility
  # Actual secrets are managed via SealedSecrets or External Secrets
  secrets:
    # Authentication & Auth secrets
    betterAuthSecret: ""

    # Payment processing
    stripeSecretKey: ""

    # Storage (S3/MinIO)
    minioRootUser: ""
    minioRootPassword: ""
    s3AccessKey: ""
    s3SecretKey: ""

    # Database secrets
    postgresPassword: ""

    # ClickHouse secrets
    clickhouseUser: "default"
    clickhousePassword: ""

    # External API keys (development defaults)
    azureApiKey: ""
    azureApiVersion: ""
    azureDeploymentName: ""
    azureBaseUrl: ""
    openaiApiKey: ""

    # Monitoring & observability
    grafanaAdminPassword: "admin"

    # Feature flags and configuration
    enablePromptSecurity: "false"
    enableCronJob: "true"

  # Configuration values (not secrets)
  config:
    s3BucketName: "helm-request-response-storage"
    s3Endpoint: "http://helicone-core-minio:9000"

  web:
    enabled: true
    image:
      repository: 849596434884.dkr.ecr.us-east-2.amazonaws.com/helicone/web
      pullPolicy: IfNotPresent
      tag: "v2025-06-17"
    replicaCount: 1
    service:
      annotations: {}
      type: ClusterIP
      port: 3000
    extraEnvVars: []
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: filevine.helicone.ai
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - filevine.helicone.ai
          secretName: heliconetest-tls
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    verticalPodAutoscaler:
      enabled: false
      updateMode: "Off"
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
      maxUnavailable: null
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          percentPolicy: 50
          periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 60
          percentPolicy: 100
          periodSeconds: 15
    postgresMigrationRunner:
      image:
        repository: 849596434884.dkr.ecr.us-east-2.amazonaws.com/helicone/migrations
        pullPolicy: IfNotPresent
        tag: "v2025-06-17"
      resources: {}

    router:
      enabled: true

  aiGateway:
    enabled: true
    image:
      repository: helicone/ai-gateway
      pullPolicy: IfNotPresent
      tag: "sha-765b2b1"
    replicaCount: 1
    service:
      annotations: {}
      type: ClusterIP
      port: 8080
    ingress:
      enabled: false
      className: "nginx"
      annotations: {}
      hosts:
        - host: filevine.helicone.ai/ai-gateway
          paths:
            - path: /
              pathType: Prefix
      tls: []
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi
    extraEnvVars:
      - name: AI_GATEWAY__SERVER__ADDRESS
        value: "0.0.0.0"
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            name: helicone-ai-gateway-secrets
            key: openai_api_key
      # Only required if deployment target == cloud
      # - name: AI_GATEWAY__MINIO__ACCESS_KEY
      #   valueFrom:
      #     secretKeyRef:
      #       name: helicone-minio-secrets
      #       key: root_user
      # - name: AI_GATEWAY__MINIO__SECRET_KEY
      #   valueFrom:
      #     secretKeyRef:
      #       name: helicone-minio-secrets
      #       key: root_password
    config:
      routers:
        default:
          load-balance:
            chat:
              strategy: latency
              targets:
                - openai
                - anthropic
      helicone:
        authentication: true

  clickhouse:
    enabled: true
    image:
      repository: clickhouse/clickhouse-server
      pullPolicy: IfNotPresent
      tag: "23.4.2.11"
    replicaCount: 1
    service:
      annotations: {}
      type: ClusterIP
      port: 8123
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    persistence:
      storageClass: "gp2-immediate"
      size: 10Gi

  # TODO Make it such that the s3 access key and secret key are the same environment variable such that it is hot-swappable with S3
  # Note: If enabled is set to false, then S3 is used instead of MinIO
  minio:
    enabled: true
    image:
      repository: minio/minio
      pullPolicy: IfNotPresent
      tag: "RELEASE.2023-05-18T00-05-36Z"
    replicaCount: 1
    service:
      annotations: {}
      type: ClusterIP
      port: 9000
      consolePort: 9001
    resources: {}
    persistence:
      storageClass: "gp2-immediate"
      size: 20Gi
    ingress:
      enabled: false
      ingressClassName: ""
      annotations: {}
    setup:
      image:
        repository: minio/mc
        tag: "latest"
        pullPolicy: IfNotPresent
      buckets:
        - "request-response-storage"

  jawn:
    enabled: true
    image:
      repository: 849596434884.dkr.ecr.us-east-2.amazonaws.com/helicone/jawn
      pullPolicy: IfNotPresent
      tag: "v2025-06-17"
    replicaCount: 1
    service:
      annotations: {}
      type: ClusterIP
      port: 8585
    extraEnvVars: []
    publicUrl: "https://filevine.helicone.ai/jawn"
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /$2
        nginx.ingress.kubernetes.io/proxy-body-size: "100m"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: filevine.helicone.ai
          paths:
            - path: /jawn(/|$)(.*)
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - filevine.helicone.ai
          secretName: heliconetest-tls
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 512Mi
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 10
      targetCPUUtilizationPercentage: 80
      targetMemoryUtilizationPercentage: 80
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          percentPolicy: 50
          periodSeconds: 60
        scaleUp:
          stabilizationWindowSeconds: 60
          percentPolicy: 100
          periodSeconds: 15

mailhog:
  enabled: true
  image:
    repository: mailhog/mailhog
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  # TODO Disaggregate this config, since not all of them are in common across the respective charts
  config:
    vercelEnv: "development"
    clickhouseHost: "http://helicone-core-clickhouse:8123"
    clickhousePort: "8123"
    clickhouseUser: "default"
    s3BucketName: "helm-request-response-storage"
    s3Endpoint: "http://helicone-core-minio:9000"
    openaiProxyPort: "8787"
    heliconeApiPort: "8788"
    anthropicProxyPort: "8789"
    gatewayApiPort: "8790"
    jawnPort: "8585"
    jawnPublicUrl: "https://filevine.helicone.ai/jawn"
    kongHttpPort: "8000"
    kongHttpsPort: "8443"
    pgrstDbSchemas: "public,storage,graphql_public"
    siteUrl: "https://filevine.helicone.ai"
    betterAuthTrustedOrigins: "https://filevine.helicone.ai,http://filevine.helicone.ai"
    additionalRedirectUrls: ""
    jwtExpiry: "3600"
    disableSignup: "false"
    apiExternalUrl: "http://localhost:8000"
    mailerUrlpathsConfirmation: "/auth/v1/verify"
    mailerUrlpathsInvite: "/auth/v1/verify"
    mailerUrlpathsRecovery: "/auth/v1/verify"
    mailerUrlpathsEmailChange: "/auth/v1/verify"
    enableEmailSignup: "true"
    enableEmailAutoconfirm: "false"
    enablePhoneSignup: "true"
    enablePhoneAutoconfirm: "true"
    studioDefaultOrganization: "Default Organization"
    studioDefaultProject: "Default Project"
    studioPort: "3000"
    imgproxyEnableWebpDetection: "true"
    functionsVerifyJwt: "false"
    dockerSocketLocation: "/var/run/docker.sock"
    googleProjectId: "GOOGLE_PROJECT_ID"
    googleProjectNumber: "GOOGLE_PROJECT_NUMBER"
    nodeEnv: "development"

# Beyla configuration (disabled in core, managed by infrastructure chart)
beyla:
  enabled: false

#################################################################################
# External Secrets Configuration
#################################################################################

# External Secrets Operator configuration for AWS Secrets Manager integration
# When enabled, secrets will be pulled from AWS Secrets Manager instead of using SealedSecrets
externalSecrets:
  # Set to true to enable External Secrets Operator integration
  enabled: true

  # Refresh interval for secret synchronization
  refreshInterval: "30s"

  # AWS Secrets Manager configuration
  aws:
    region: "us-west-2"

  # Service account for AWS authentication
  serviceAccount:
    name: "external-secrets-sa"

  # Prefix for secret keys in AWS Secrets Manager
  secretPrefix: "helicone"
#################################################################################
# Sealed Secrets Configuration
#################################################################################

# Secrets are now managed via Bitnami Sealed Secrets for GitOps-friendly secret management.
#
# To generate encrypted secrets:
#   1. Install kubeseal CLI: https://github.com/bitnami-labs/sealed-secrets
#   2. Run: ./scripts/generate-sealed-secrets.sh [environment] [namespace]
#   3. Commit the encrypted secrets to Git (they are safe to store)
#
# The SealedSecret resources will automatically create the required Kubernetes Secrets
# that the application components reference.
