apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: helicone-web
spec:
  parentRefs:
  - name: shared-gateway
    namespace: infra
  hostnames:
  - "helicone-web.infra-test-03.hp.ragdl.ai"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: helicone-core-web
      port: 3000
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: helicone-web-hc-config
  namespace: helicone
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 3
    healthyThreshold: 1
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /signin
  targetRef:
    group: ""
    kind: Service
    name: helicone-core-web
