{{- if .Values.helicone.aiGateway.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: helicone-ai-gateway-secrets
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
type: Opaque
data:
  # TODO Make sure that the container doesn't fail if any of these secrets are not set.
  helicone_api_key: {{ .Values.helicone.config.heliconeApiKey | default "HELICONE_API_KEY" | toString | b64enc }}
  openai_api_key: {{ .Values.helicone.config.openaiApiKey | default "OPENAI_API_KEY" | toString | b64enc }}
  anthropic_api_key: {{ .Values.helicone.config.anthropicApiKey | default "ANTHROPIC_API_KEY" | toString | b64enc }}
  gemini_api_key: {{ .Values.helicone.config.geminiApiKey | default "GEMINI_API_KEY" | toString | b64enc }}
{{- end }}