{{- if .Values.helicone.helix.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helicone-helix
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "helicone.helix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "helicone.helix.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: helicone-helix
          image: "{{ .Values.helicone.helix.image.repository }}:{{ .Values.helicone.helix.image.tag }}"
          imagePullPolicy: {{ .Values.helicone.helix.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5678
              protocol: TCP
          command: ["/usr/local/bin/llm-proxy", "-c", "/app/config/demo.yaml"]
          volumeMounts:
            - name: config
              mountPath: /app/config
          env:
            - name: PROXY__SERVER__ADDRESS
              value: "0.0.0.0"
            - name: PROXY__MINIO__ACCESS_KEY
              value: "minioadmin"
            - name: PROXY__MINIO__SECRET_KEY
              value: "minioadmin"
            {{ include "helicone.env.helixProxyHeliconeApiKey" . }}
            {{ include "helicone.env.helixOpenaiApiKey" . }}
            {{ include "helicone.env.helixAnthropicApiKey" . }}
            {{ include "helicone.env.helixGeminiApiKey" . }}
            - name: OTEL_METRIC_EXPORT_INTERVAL
              value: "5000"
            {{ include "helicone.env.helixHeliconeApiKey" . }}
      volumes:
        - name: config
          configMap:
            name: helicone-config
    #   {{- if .Values.beyla.enabled }}
    #   volumes:
    #     - name: beyla-config
    #       configMap:
    #         name: {{ include "helicone.fullname" . }}-beyla-config
    #     - name: var-run-beyla
    #       emptyDir: {}
    #   {{- end }}
{{- end }}