apiVersion: v1
kind: Secret
metadata:
  name: helicone-minio-secrets
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
type: Opaque
data:
  root_user: {{ .Values.helicone.secrets.minioRootUser | default "" | b64enc }}
  root_password: {{ .Values.helicone.secrets.minioRootPassword | default "" | b64enc }}
