# Main secrets for database, S3, and core functionality
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: helicone-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    postgres-password: "PLACEHOLDER-ENCRYPT-YOUR-POSTGRES-PASSWORD"
    access_key: "PLACEHOLDER-ENCRYPT-YOUR-S3-ACCESS-KEY"
    secret_key: "PLACEHOLDER-ENCRYPT-YOUR-S3-SECRET-KEY"
    minio-root-user: "PLACEHOLDER-ENCRYPT-YOUR-MINIO-ROOT-USER"
    minio-root-password: "PLACEHOLDER-ENCRYPT-YOUR-MINIO-ROOT-PASSWORD"
  template:
    metadata:
      name: helicone-secrets
      labels:
        {{- include "helicone.labels" . | nindent 8 }}
    type: Opaque
    data:
      # Configuration values (not secrets)
      bucket_name: {{ .Values.helicone.config.s3BucketName | default "helm-request-response-storage" | b64enc }}
      endpoint: {{ .Values.helicone.config.s3Endpoint | default "http://helicone-core-minio:9000" | b64enc }}

---
# Web application secrets
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: helicone-web-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # NOTE: These are PLACEHOLDER values - replace with your actual encrypted secrets
    BETTER_AUTH_SECRET: "PLACEHOLDER-ENCRYPT-YOUR-BETTER-AUTH-SECRET"
    STRIPE_SECRET_KEY: "PLACEHOLDER-ENCRYPT-YOUR-STRIPE-SECRET-KEY"
  template:
    metadata:
      name: helicone-web-secrets
      labels:
        {{- include "helicone.labels" . | nindent 8 }}
    type: Opaque

---
# MinIO specific secrets
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: helicone-minio-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # NOTE: These are PLACEHOLDER values - replace with your actual encrypted secrets
    root_user: "PLACEHOLDER-ENCRYPT-YOUR-MINIO-ROOT-USER"
    root_password: "PLACEHOLDER-ENCRYPT-YOUR-MINIO-ROOT-PASSWORD"
  template:
    metadata:
      name: helicone-minio-secrets
      labels:
        {{- include "helicone.labels" . | nindent 8 }}
    type: Opaque

---
{{- if and .Values.helicone.aiGateway.enabled }}
# AI Gateway API Keys
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: helicone-ai-gateway-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # NOTE: These are PLACEHOLDER values - replace with your actual encrypted secrets
    openai_api_key: "PLACEHOLDER-ENCRYPT-YOUR-OPENAI-API-KEY"
    anthropic_api_key: "PLACEHOLDER-ENCRYPT-YOUR-ANTHROPIC-API-KEY"
    gemini_api_key: "PLACEHOLDER-ENCRYPT-YOUR-GEMINI-API-KEY"
    helicone_api_key: "PLACEHOLDER-ENCRYPT-YOUR-HELICONE-API-KEY"
  template:
    metadata:
      name: helicone-ai-gateway-secrets
      labels:
        {{- include "helicone.labels" . | nindent 8 }}
    type: Opaque
{{- end }}

---
{{- if .Values.helicone.clickhouse.enabled }}
# ClickHouse secrets
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "clickhouse.name" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
spec:
  encryptedData:
    # NOTE: These are PLACEHOLDER values - replace with your actual encrypted secrets
    user: "PLACEHOLDER-ENCRYPT-YOUR-CLICKHOUSE-USER"
    # TODO: ClickHouse doesn't yet support a password. This is a placeholder.
    # password: "PLACEHOLDER-ENCRYPT-YOUR-CLICKHOUSE-PASSWORD"
  template:
    metadata:
      name: {{ include "clickhouse.name" . }}-secrets
      labels:
        {{- include "helicone.labels" . | nindent 8 }}
    type: Opaque
{{- end }} 