apiVersion: v1
kind: Secret
metadata:
  name: helicone-secrets
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
type: Opaque
data:
  access_key: {{ .Values.helicone.secrets.s3AccessKey | b64enc }}
  secret_key: {{ .Values.helicone.secrets.s3SecretKey | b64enc }}
  bucket_name: {{ .Values.helicone.config.s3BucketName | b64enc }}
  endpoint: {{ .Values.helicone.config.s3Endpoint | b64enc }}
  postgres-password: {{ .Values.helicone.secrets.postgresPassword | b64enc }}
  minio-root-user: {{ .Values.helicone.secrets.minioRootUser | b64enc }}
  minio-root-password: {{ .Values.helicone.secrets.minioRootPassword | b64enc }}
