{{- if .Values.helicone.clickhouse.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.name" . }}-secrets
  labels:
    {{- include "helicone.labels" . | nindent 4 }}
type: Opaque
data:
  user: {{ .Values.helicone.secrets.clickhouseUser | default "default" | b64enc }}
  # TODO Clickhouse doesn't yet support a password. This is a placeholder. For deployments to clickhouse, make sure to add secret support.
  # password: {{ .Values.helicone.secrets.clickhousePassword | default "" | b64enc }}
{{- end }}